"""Initial tables for FCA categorization

Revision ID: 3e6cb24a5fda
Revises: 
Create Date: 2024-10-28 20:04:18.934586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6cb24a5fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fca_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fca_sections_category'), 'fca_sections', ['category'], unique=False)
    op.create_index(op.f('ix_fca_sections_id'), 'fca_sections', ['id'], unique=False)
    op.create_index(op.f('ix_fca_sections_title'), 'fca_sections', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fca_sections_title'), table_name='fca_sections')
    op.drop_index(op.f('ix_fca_sections_id'), table_name='fca_sections')
    op.drop_index(op.f('ix_fca_sections_category'), table_name='fca_sections')
    op.drop_table('fca_sections')
    # ### end Alembic commands ###
